# Generated by Django 4.1.7 on 2023-06-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_ID_no', models.CharField(max_length=12, unique=True)),
                ('company_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('chief_contractor', models.CharField(max_length=100, unique=True)),
                ('chief_contractor_phone_no', models.CharField(max_length=12, unique=True)),
                ('contracting_team_member_1', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Procurement Department',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('project_location', models.CharField(max_length=100)),
                ('sqm_rate_or_lm', models.CharField(max_length=50)),
                ('commencement_date', models.DateTimeField()),
                ('tender_no', models.CharField(max_length=20, unique=True)),
                ('site_location', models.CharField(max_length=80)),
                ('floor_area', models.CharField(max_length=20)),
                ('contract_sum', models.CharField(max_length=20)),
                ('payments_made', models.CharField(max_length=20)),
                ('payment_status', models.BooleanField(choices=[(0, 'Paid'), (1, 'Pending')], default=1)),
                ('work_status', models.BooleanField(choices=[(0, 'started'), (1, 'completed')], default=0)),
                ('completed', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('contract_period_months', models.PositiveIntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracting_company', to='users.contractor')),
                ('procurrement_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement', to='users.procurement_department')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600)),
                ('images', models.ImageField(upload_to='Progress_Images/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyname', to='users.contractor')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectname', to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_name', models.CharField(max_length=80, unique=True)),
                ('checklist_document', models.FileField(blank=True, null=True, upload_to='Checklist_Documents/')),
                ('contract_period_months', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('main_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='users.contractor')),
                ('procurrement_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procuring_dpt', to='users.procurement_department')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
