# Generated by Django 4.1.1 on 2023-06-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurement_department',
            options={'verbose_name': 'Procurement Department'},
        ),
        migrations.AlterModelTable(
            name='procurement_department',
            table='Procurement_Department',
        ),
    ]
