# Generated by Django 4.1.1 on 2023-06-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_procurement_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='procurement_department',
            table='Tables',
        ),
    ]
