# Generated by Django 4.2.2 on 2023-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='company_name',
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='phase',
            field=models.CharField(choices=[('1', 'Approval'), ('2', 'Start'), ('3', 'Foundation'), ('4', 'Completion')], default='1', max_length=1),
        ),
    ]
