# Generated by Django 4.2.2 on 2023-07-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectprogress',
            old_name='main_images',
            new_name='main_image',
        ),
    ]
