# Generated by Django 4.2.2 on 2023-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_main_images_projectprogress_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='main_image',
            field=models.ImageField(upload_to='Progress_Images/'),
        ),
    ]
