# Generated by Django 4.2.2 on 2023-07-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_projectprogress_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='Progress_Documents/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='Progress_Documents/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='Progress_Documents/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='document_4',
            field=models.FileField(blank=True, null=True, upload_to='Progress_Documents/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='document_5',
            field=models.FileField(blank=True, null=True, upload_to='Progress_Documents/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_11',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_12',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_13',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_14',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_15',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_16',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_17',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_18',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_19',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_20',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_21',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_22',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_23',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_24',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_25',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_26',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_27',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_28',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_29',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_30',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_31',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_32',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='Progress_Images/'),
        ),
    ]
