# Generated by Django 4.2.2 on 2023-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_projectprogress_document_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_7',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_8',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contracting_team_member_9',
            field=models.CharField(max_length=100),
        ),
    ]
